### ISSUE TITLE
instructorCourseEnrollSave causing nullpointer exception when the browser reloads the page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1255]
_From [dam...@gmail.com](https://code.google.com/u/114919422028123491955/) on October 22, 2013 11:22:51_

This is the scenario:
User does some enrolling. instructorCourseEnrollSave is the last page loaded.
User quits browser.
Next day, he restarts browser and the page is reloaded by the browser automatically.

The above reloading seems to throw a NPE. Stack trace below:

java.lang.AssertionError: null
	at teammates.common.util.Assumption.fail(Assumption.java:56)
	at teammates.common.util.Assumption.assertTrue(Assumption.java:25)
	at teammates.common.util.Assumption.assertNotNull(Assumption.java:252)
	at teammates.common.util.Assumption.assertNotNull(Assumption.java:244)
	at teammates.ui.controller.InstructorCourseEnrollSaveAction.execute(InstructorCourseEnrollSaveAction.java:27)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:122)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:48)
	at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:34)

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1256_

**Comment by damithc** [comment]
No longer relevant
