### ISSUE TITLE
logger warning not proper when admin user(not an instructor) sign in to instructor page

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#1718]
_From [franklin...@gmail.com](https://code.google.com/u/105954579351330227091/) on March 15, 2014 00:53:59_

What steps will reproduce the problem? 1.start the server
2.go to  root url(localhost:8888/)
3.click instructor login
4.key in a non-instructor user account and make sure to select "Sign in as administrator" What is the expected output? What do you see instead? Expected: (maybe not authorized to view the page response? which is right in this case)
Actual: the page is displayed. but the logger message is not right:
"""
WARNING: TEAMMATESLOG|||page|||Servlet Action Failure|||true|||Unknown|||Unknown|||Unknown|||Unknown|||<span class="color_red">Servlet Action failure in page<br>class teammates.common.exception.UnauthorizedAccessException: 
teammates.common.exception.UnauthorizedAccessException: User test@example.com does not have admin privilleges
	at teammates.logic.api.GateKeeper.verifyInstructorPrivileges(GateKeeper.java:121)
	at teammates.ui.controller.InstructorHomePageAction.execute(InstructorHomePageAction.java:22)
	at ...(omitted)
"""
the user is admin, but the logger message is saying the user does not  have admin privilleges--instead, it should be something like such an instructor does not exist Please use labels and text to provide additional information. logger

_Original issue: http://code.google.com/p/teammatespes/issues/detail?id=1721_

**Comment by damithc** [comment]
outdated. closing.
