### ISSUE TITLE
Omitting archived courses from dropdown list makes the page slower

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2879]
I cannot load my 'sessions' page in V5.31. The AJAX page doesn't load. Possibly due to #2852 ?

**Comment by damithc** [comment]
I've rolled back to V5.30

**Comment by LowWeiLin** [comment]
Is there any error? #2872 has not been merged and might help, but i'm not sure. Need to look into it.

**Comment by damithc** [comment]
There is no error message. There were some 'API call not completed' errors.
Server instances seem to die too.

**Comment by damithc** [comment]
Most others are not affected, but instructors who have many sessions are
affected. May be too many additional DB calls?

**Comment by damithc** [comment]
I got this error a lot, possibly related. This causes the server to die.
A problem was encountered with the process that handled this request,
causing it to exit. This is likely to cause a new process to be used for
the next request to your application. (Error code 202)

**Comment by damithc** [comment]
Here's the full error from server logs. Seems like a read operation times out.

teammates.ui.controller.ControllerServlet doPost: TEAMMATESLOG|||page|||System Error Report|||true|||Unknown|||Unknown|||Unknown|||Unknown||||||/page/instructorFeedbacksPage?user=damith&isusingAjax=on
W 2015-01-14 14:42:11.743
/page/instructorFeedbacksPage
com.google.apphosting.api.ApiProxy$CancelledException: The API call datastore_v3.Put() was explicitly cancelled.
	at com.google.apphosting.runtime.ApiProxyImpl$5.get(ApiProxyImpl.java:386)
	at com.google.apphosting.runtime.ApiProxyImpl$5.get(ApiProxyImpl.java:383)
	at com.google.appengine.tools.appstats.RecordingFuture.get(RecordingFuture.java:108)
	at com.google.appengine.tools.appstats.RecordingFuture.get(RecordingFuture.java:20)
	at com.google.appengine.tools.appstats.RecordingFuture.get(RecordingFuture.java:108)
	at com.google.appengine.tools.appstats.Recorder.processRecordingFuture(Recorder.java:397)
	at com.google.appengine.tools.appstats.Recorder.processAsyncRpc(Recorder.java:370)
	at com.google.appengine.tools.appstats.RecordingFuture.maybeRecordStats(RecordingFuture.java:140)
	at com.google.appengine.tools.appstats.RecordingFuture.get(RecordingFuture.java:110)
	at com.google.appengine.tools.appstats.RecordingFuture.get(RecordingFuture.java:20)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:92)
	at com.google.appengine.api.datastore.Batcher$ReorderingMultiFuture.get(Batcher.java:132)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:92)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:92)
	at com.google.appengine.api.utils.FutureWrapper.get(FutureWrapper.java:92)
	at com.google.appengine.api.datastore.FutureHelper.getInternal(FutureHelper.java:76)
	at com.google.appengine.api.datastore.FutureHelper.quietGet(FutureHelper.java:36)
	at com.google.appengine.api.datastore.DatastoreServiceImpl.put(DatastoreServiceImpl.java:58)
	at com.google.apphosting.runtime.jetty.DatastoreSessionStore.saveSession(DatastoreSessionStore.java:94)
	at com.google.apphosting.runtime.jetty.SessionManager$AppEngineSession.save(SessionManager.java:159)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:41)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:254)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:484)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:438)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:445)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:220)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:309)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:301)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:442)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:251)
	at java.lang.Thread.run(Thread.java:724)
W

**Comment by damithc** [comment]
In 5.30, loading the new session form takes about 5s and the ajax part takes about 20s. In 5.31, the form takes about 45s, and ajax thing keeps going forever.

**Comment by damithc** [comment]
You can use appstats to see the number of database reads. It's already enabled for TEAMMATES. Just go to http://localhost:8888/appstats

**Comment by LowWeiLin** [comment]
I'm modifying the code from PR #2872.
It seems like using the CourseDetailsBundle data structure incurs more db calls.
After removing the use of it, appstats show a huge reduction in the timing from 223ms to 77ms (only one course, 3 feedback sessions)

**Comment by damithc** [comment]
Tried it on the live server. Seems to work. Good job!

**Comment by LowWeiLin** [comment]
Is the performance fine? Hopefully its faster than V5.30...

**Comment by damithc** [comment]
I tried loading my sessions page on both versions, three times each:
Loading the sessions list:
V5.30: 14s, 17s, 21s,
V5.32: 13s, 13s, 10s
Perhaps there is a marginal improvement. It is possible that trying to
remove archived sessions in fact requires more db queries than displaying
all sessions. However, it certainly reduces the clutter in the page. Most
likely we gained in usability and lost in performance and cost :-p

**Comment by damithc** [comment]
I archived a few more courses which had many sessions. Now there is a
definite improvement. Now 5.32 takes about 2s to load the session list
while 5.30 takes about 14s. So it has not been in vain after all :-)

**Comment by LowWeiLin** [comment]
Great! There's still room for improvement on that page. Will work on it in #2880

**Comment by damithc** [comment]
The reason why there was not much change previously was actually a bug. The
sessions page does not cater for legacy data where the archiving was done
as course level. So most of the sessions from my old courses were showing
up anyway. They go away only after I unarchive them and archive them again.
Perhaps we can write a script to migrate the data instead of catering for
legacy data? i.e. if a course has the archived flag set to true, we set the
archive flag for all instructors of that course.
