### ISSUE TITLE
ArrayIndexOutOfBoundsException in rubrics question

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2900]
Here's the error message:

-1
Request Path /page
Request Parameters {rubricChoice-14::10, rubricChoice-13::9, rubricChoice-12::8, rubricNumRows::5, rubricChoice-4::0, rubricChoice-6::2, rubricChoice-5::1, constSumToRecipients::false, rubricChoice-8::4, rubricChoice-7::3, rubricChoice-9::5, numofrecipients::1, rubricDesc-0-14::Excellent, rubricDesc-0-13::, rubricDesc-0-12::, rubricDesc-0-11::, rubricDesc-0-10::, rubricDesc-1-11::, rubricDesc-1-10::, recipienttype::OWN_TEAM_MEMBERS, rubricDesc-1-13::, rubricDesc-1-12::, rubricDesc-1-14::, rubricChoice-10::6, rubricChoice-11::7, constSumPoints::100, showrecipientto::RECEIVER,INSTRUCTORS, rubricNumCols::15, rubricDesc-3-14::, rubricDesc-3-10::, rubricDesc-3-11::, rubricDesc-3-12::, rubricDesc-3-13::, showgiverto::INSTRUCTORS, questionnum::6//6, courseid::101, rubricDesc-1-7::, noofchoicecreated::2//2//2, rubricDesc-1-8::, rubricDesc-1-9::, rubricDesc-3-9::, rubricDesc-1-4::, rubricDesc-1-5::, rubricDesc-1-6::, numscalemin::1, fsname::Test 2, receiverLeaderCheckbox::RECEIVER, questiontype::RUBRIC, numscalemax::5, rubricDesc-3-6::, rubricDesc-3-5::, rubricDesc-3-8::, rubricDesc-3-7::, rubricDesc-3-4::, showresponsesto::RECEIVER,INSTRUCTORS, constSumPointsPerOption::false, numofrecipientstype::max, constSumOption-1::, constSumOption-0::, rubricDesc-0-7::, generatedOptions::NONE//NONE//NONE, rubricDesc-0-6::, rubricDesc-0-5::Very Poor, rubricDesc-0-4::Did not submit, rubricDesc-0-9::, rubricDesc-0-8::, numscalestep::1, rubricDesc-2-14::, rubricDesc-2-13::, rubricDesc-2-12::, rubricDesc-2-11::, rubricDesc-2-10::, questiontext::Rate, mcqOption-1::, mcqOption-0::, rubricSubQn-0::Covered all relevant material with full thought, insight, and analysis, rubricSubQn-3::The submission was free of grammatical or stylistic errors , rubricSubQn-4::The work was of quality and I learned from it , rubricSubQn-1::Explained topics clearly with connections to previous or current and/or to real-life situations or examples , rubricSubQn-2::Organized the topics and ideas in a clear and concise manner , rubricDesc-2-5::, rubricDesc-2-4::, rubricDesc-2-7::, rubricDesc-2-6::, rubricDesc-2-9::, rubricDesc-2-8::, rubricDesc-4-6::, rubricDesc-4-7::, rubricDesc-4-4::, rubricDesc-4-5::, msqOption-0::, rubricDesc-4-9::, rubricDesc-4-8::, msqOption-1::, rubricDesc-4-10::, rubricDesc-4-13::, rubricDesc-4-14::, rubricDesc-4-11::, rubricDesc-4-12::, givertype::STUDENTS, user::abc}
Stack Trace

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:371)
	at java.util.ArrayList.get(ArrayList.java:384)
	at teammates.common.datatransfer.FeedbackRubricQuestionDetails.extractQuestionDetails(FeedbackRubricQuestionDetails.java:89)
	at teammates.common.datatransfer.FeedbackQuestionType.getFeedbackQuestionDetailsInstance(FeedbackQuestionType.java:60)
	at teammates.common.datatransfer.FeedbackQuestionDetails.createQuestionDetails(FeedbackQuestionDetails.java:158)
	at teammates.ui.controller.InstructorFeedbackQuestionAddAction.extractFeedbackQuestionData(InstructorFeedbackQuestionAddAction.java:117)
	at teammates.ui.controller.InstructorFeedbackQuestionAddAction.execute(InstructorFeedbackQuestionAddAction.java:33)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:328)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:58)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:142)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:254)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:484)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:438)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:445)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:220)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:309)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:301)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:442)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:251)
	at java.lang.Thread.run(Thread.java:724)

**Comment by LowWeiLin** [comment]
This error occurs when the first column/choice is deleted. Fixing the issue now.
