### ISSUE TITLE
Assertion failure in FeedbackQuestionSubmissionEditPageAction

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3357]
null

Request Path /page 
Request Parameters {courseid::TCP-122_2015, fsname::Peer assessment } 
Stack Trace

java.lang.AssertionError: null
	at teammates.common.util.Assumption.fail(Assumption.java:58)
	at teammates.common.util.Assumption.assertTrue(Assumption.java:27)
	at teammates.common.util.Assumption.assertNotNull(Assumption.java:254)
	at teammates.common.util.Assumption.assertNotNull(Assumption.java:246)
	at teammates.ui.controller.FeedbackQuestionSubmissionEditPageAction.execute(FeedbackQuestionSubmissionEditPageAction.java:22)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:332)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:58)
	at teammates.ui.controller.ControllerServlet.doGet(ControllerServlet.java:37)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:142)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:254)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:527)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:220)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:251)
	at java.lang.Thread.run(Thread.java:745)

**Comment by MrFool** [comment]
This happens during the test suite as well, able to pass after some persistent tries though

**Comment by wkurniawan07** [comment]
@MrFool in which test does it fail?

**Comment by MrFool** [comment]
testExecuteAndPostProcess

**Comment by wkurniawan07** [comment]
a bit too specific, how about the java file name for the test?

**Comment by MrFool** [comment]
I'll ping again when I see it fail (I'll keep a special lookout for it), recent few test suite I haven't been seeing it fail, it's an on and off thing.

**Comment by wkurniawan07** [comment]
Well sure, although I won't be able to work on it until my exam ends (this wed).

**Comment by MrFool** [comment]
![screen shot 2015-05-08 at 1 49 38 pm](https://cloud.githubusercontent.com/assets/6291947/7531241/16152f40-f589-11e4-848f-023aaf83967d.png)
![screen shot 2015-05-08 at 1 49 31 pm](https://cloud.githubusercontent.com/assets/6291947/7531243/1640459a-f589-11e4-9e50-d1e5b522fd5c.png)
![screen shot 2015-05-08 at 1 49 20 pm](https://cloud.githubusercontent.com/assets/6291947/7531244/1665313e-f589-11e4-8cc1-482f66315e6e.png)

**Comment by wkurniawan07** [comment]
@MrFool I managed to find out the cause of the one you posted up there  (StudentFeedbackResultsPageActionTest), but I'm pretty sure it's not relevant to the issue at hand.

**Comment by wkurniawan07** [comment]
Alright I found out the cause of this issue. Now I'm trying to find a way to get around it.

**Comment by wkurniawan07** [comment]
This is a copy of #2904, btw

**Comment by wkurniawan07** [comment]
Ah, I forgot to explain the one above (`StudentFeedbackResultsPageActionTest`).
Between lines 220 and 226, time will elapse, perhaps just a few milliseconds or even hundreds of microseconds. However, if the time elapsed is enough to change the recorded time (precision up to seconds) in the `expectedInfoList`, the test will fail.
For example:
Line 220 pageData, resultVisibleFromTime 00:00:00.500
Line 226 dataBundle, resultVisibleFromTime 00:00:00.502
This is perfectly fine. But if this happens:
Line 220 pageData, resultVisibleFromTime 00:00:00.999
Line 226 dataBundle, resultVisibleFromTime 00:00:01.001
The test will fail.
Dr @damithc can I ignore this one? It's not feasible to try to work it around, besides it actually takes a miracle to happen.
