### ISSUE TITLE
StudentProfilePageUiTest is failing on live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4156]
failing at line `195         getProfilePicturePage(studentId, "random-StRing123").verifyIsErrorPage(expectedFilename);`

**Comment by thyageshm** [comment]
Hi sir, could I have the exact failure message? When I tried manually on the live website, the output seems to be fine.

**Comment by damithc** [comment]
This is the page I see 
![image](https://cloud.githubusercontent.com/assets/1673303/9491806/640191f2-4c24-11e5-9866-1e4160fc97be.png)

Trace:
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at teammates.test.pageobjects.AppPage.createNewPage(AppPage.java:1078)
	at teammates.test.pageobjects.AppPage.getNewPageInstance(AppPage.java:166)
	at teammates.test.cases.ui.browsertests.BaseUiTestCase.loginAdminToPage(BaseUiTestCase.java:76)
	at teammates.test.cases.ui.browsertests.StudentProfilePageUiTest.getProfilePicturePage(StudentProfilePageUiTest.java:226)
	at teammates.test.cases.ui.browsertests.StudentProfilePageUiTest.testAjaxPictureUrl(StudentProfilePageUiTest.java:195)
	at teammates.test.cases.ui.browsertests.StudentProfilePageUiTest.allTests(StudentProfilePageUiTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at teammates.test.pageobjects.AppPage.createNewPage(AppPage.java:1074)
	... 29 more
Caused by: java.lang.IllegalStateException: Not in the correct page!
	at teammates.test.pageobjects.AppPage.<init>(AppPage.java:148)
	at teammates.test.pageobjects.StudentProfilePicturePage.<init>(StudentProfilePicturePage.java:13)
	... 34 more

```
