### ISSUE TITLE
IllegalArgumentException: name cannot be null or empty

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4540]
Got this while testing:

name cannot be null or empty

Actual user abc
Request Method POST
User Agent Mozilla/5.0 (Windows NT 6.1; WOW64; rv:41.0) Gecko/20100101 Firefox/41.0
Request Url https://5-59-dot-teammatesv4.appspot.com/page/instructorCourseEditPage
Request Path /page
Request Parameters {instructoremail::InsCrsEdit.Helper@gmail.tmt, courseeditmainindex::1, user::InsCrsEdit.test, courseid::}
Stack Trace

java.lang.IllegalArgumentException: name cannot be null or empty
	at com.google.appengine.api.datastore.KeyFactory.createKey(KeyFactory.java:82)
	at com.google.appengine.api.datastore.KeyFactory.createKey(KeyFactory.java:77)
	at com.google.appengine.api.datastore.KeyFactory.createKey(KeyFactory.java:65)
	at org.datanucleus.store.appengine.query.DatastoreQuery.internalPkToKey(DatastoreQuery.java:1677)
	at org.datanucleus.store.appengine.query.DatastoreQuery.addLeftPrimaryExpression(DatastoreQuery.java:1322)
	at org.datanucleus.store.appengine.query.DatastoreQuery.addExpression(DatastoreQuery.java:1070)
	at org.datanucleus.store.appengine.query.DatastoreQuery.addFilters(DatastoreQuery.java:1031)
	at org.datanucleus.store.appengine.query.DatastoreQuery.performExecute(DatastoreQuery.java:238)
	at org.datanucleus.store.appengine.query.JDOQLQuery.performExecute(JDOQLQuery.java:92)
	at org.datanucleus.store.query.Query.executeQuery(Query.java:1489)
	at org.datanucleus.store.query.Query.executeWithArray(Query.java:1371)
	at org.datanucleus.jdo.JDOQuery.execute(JDOQuery.java:243)
	at teammates.storage.api.CoursesDb.getCourseEntity(CoursesDb.java:159)
	at teammates.storage.api.CoursesDb.getCourse(CoursesDb.java:59)
	at teammates.logic.core.CoursesLogic.getCourse(CoursesLogic.java:122)
	at teammates.logic.api.Logic.getCourse(Logic.java:685)
	at teammates.ui.controller.InstructorCourseEditPageAction.execute(InstructorCourseEditPageAction.java:29)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:337)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:142)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:147)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:457)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
	at java.lang.Thread.run(Thread.java:745)

**Comment by damithc** [comment]
Still happening.

**Comment by himanshujoshi5992** [comment]
I think you would have assigned a null value to some some variable in your code.
