### ISSUE TITLE
NullPointerException in InstructorFeedbackQuestionEditAction

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4705]
java.lang.NullPointerException
	

Actual user abc
Request Method POST 
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.10 
Request Url https://teammatesv4.appspot.com/page/instructorFeedbackQuestionEdit 
Request Path /page 
Request Parameters {showresponsesto::RECEIVER,OWN_TEAM_MEMBERS,RECEIVER_TEAM_MEMBERS,INSTRUCTORS, showrecipientto::RECEIVER,INSTRUCTORS, numofrecipients::1, questionedittype::edit, questiontext::Using the Situation-Behavior-Impact method of feedback discussed in class, provide one statement regarding the student's contribution to date., fsname::Feedback assignment #1, questionid::abczfnRlYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgPbkoI0KDA, numofrecipientstype::max, recipienttype::OWN_TEAM_MEMBERS_INCLUDING_SELF, showgiverto::INSTRUCTORS, receiverLeaderCheckbox::RECEIVER, questiontype::CONTRIB, questionnum::1//1, givertype::STUDENTS, user::abc, courseid::MGMT210-spring2016} 
Stack Trace

java.lang.NullPointerException
	at teammates.logic.core.FeedbackQuestionsLogic.updateFeedbackQuestionNumber(FeedbackQuestionsLogic.java:552)
	at teammates.logic.api.Logic.updateFeedbackQuestionNumber(Logic.java:1810)
	at teammates.ui.controller.InstructorFeedbackQuestionEditAction.editQuestion(InstructorFeedbackQuestionEditAction.java:97)
	at teammates.ui.controller.InstructorFeedbackQuestionEditAction.execute(InstructorFeedbackQuestionEditAction.java:49)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:337)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:468)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:256)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
	at java.lang.Thread.run(Thread.java:745)

**Comment by unyoungwax** [comment]
One way to reproduce this bug is as follows:
1. Open the "Edit Feedback Session" page for the same session in 2 browser tabs.
2. Delete a question in one tab.
3. Edit the same question in another tab and save changes.

Currently, errorPage.jsp will be displayed if the bug occurs. Should we
1. Display entityNotFoundPage.jsp OR
2. Display a status message stating that "the edited question no longer exists" in "Edit Feedback Session" page?

**Comment by unyoungwax** [comment]
In `InstructorFeedbackQuestionEditAction.java` around line 84, it seems that the condition of the if-statement is always true even if the question number is not edited, leading to `FeedbackQuestionLogic.updateFeedbackQuestionNumber` that causes the bug. The bug occurs before the check (whether the edited question exists) is performed in `FeedbackQuestionLogic.updateFeedbackQuestion`. In the method, `EntityDoesNotExistException` is thrown if the edited question does not exist, .

**Comment by kanghj** [comment]
@unyoungwax, can you make a new issue for that incorrect if-statement? Fixing that won't fix this issue, right? 

Another possible cause of this NPE is eventual consistency, such as if the instructor modifies a question right after creating it.
