### ISSUE TITLE
InstructorStudentListAjaxPageAction: UnknownFormatConversionException Conversion = 'm'

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4739]
Error Message: teammates.ui.controller.ControllerServlet doPost: TEAMMATESLOG|||page|||System Error Report|||true|||Unknown|||Unknown|||abc%manchester.ac.uk@gtempaccount.com|||Unknown|||TEAMMATES (5.65): New System Exception: Conversion = 'm'
Show/Hide Details >>
Error Message

Conversion = 'm'

Actual user abc%manchester.ac.uk@gtempaccount.com
Request Method POST
User Agent Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.101 Safari/537.36
Request Url https://teammatesv4.appspot.com/page/instructorStudentListAjaxPage
Request Path /page
Request Parameters {courseidx::0, user::abc%manchester.ac.uk@gtempaccount.com, courseid::CHEN30012-30022-30032}
Stack Trace

java.util.UnknownFormatConversionException: Conversion = 'm'
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2646)
	at java.util.Formatter$FormatSpecifier.(Formatter.java:2675)
	at java.util.Formatter.parse(Formatter.java:2528)
	at java.util.Formatter.format(Formatter.java:2469)
	at java.util.Formatter.format(Formatter.java:2423)
	at java.lang.String.format(String.java:2792)
	at teammates.ui.controller.InstructorStudentListAjaxPageAction.execute(InstructorStudentListAjaxPageAction.java:50)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:337)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:143)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:148)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:468)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:256)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
	at java.lang.Thread.run(Thread.java:745)

|||/page/instructorStudentListAjaxPage?courseid=CHEN30012-30022-30032&user=abc%25manchester.ac.uk%40gtempaccount.com&courseidx=0|||ryan.mcgeown%xyz@gtempaccount.com%2016020917322064

**Comment by damithc** [comment]
@thyageshm can you look into this? Seems to be coming from a line related to Profile pic. One instructor cannot see the student list because of this.

**Comment by damithc** [comment]
This particular instructor has a Google ID like this `abc.mcgeown%manchester.ac.uk@gtempaccount.com`
Perhaps `%m` is causing this problem.

**Comment by thyageshm** [comment]
Yup, it is because we have started using string formatter to generate the photourl and the `%m` in the name is being wrongly recognized as a placeholder in the `String.format` function.

**Comment by damithc** [comment]
Use a safer way to create the string? If we can include the patch in this release, we don't have to do a hot fix later.

**Comment by thyageshm** [comment]
I believe it is a remnant of #3781. I think we did not expect the instructor id to contain a '%' sign.
I think we can double up the % sign in the string to fix this.

eg: abc.mcgeown%manchester.ac.uk@gtempaccount.com to abc.mcgeown%**%**manchester.ac.uk@gtempaccount.com

**Comment by thyageshm** [comment]
I believe this has been the case even before #3781

**Comment by thyageshm** [comment]
I will send in a fix soon

**Comment by damithc** [comment]
I don't think this % is added by us. It is in the original Google ID. We shouldn't use string formatter unless we have a guarantee about the rest of the string.

**Comment by thyageshm** [comment]
Yes, we shouldn't have used it. The problem arose when we added userIds to the urls and overlooked this problem.
The format currently being used is: 
```
String photoUrl = Const.ActionURIs.STUDENT_PROFILE_PICTURE
                        + "?" + Const.ParamsNames.STUDENT_EMAIL
                        + "=%s&" + Const.ParamsNames.COURSE_ID
                        + "=%s&" + Const.ParamsNames.USER_ID + "=" + account.googleId;
```

The only part of the string that is out of our control is the account.googleId. If we escape that string, we can safely use the formatter

**Comment by thyageshm** [comment]
A safer way would be to append the userid parameter AFTER the `String.format` call

**Comment by thyageshm** [comment]
@damithc what do you think?

**Comment by thyageshm** [comment]
A similar thing is done in line 66 of InstructorCourseDetailsPageData.java

**Comment by damithc** [comment]
Yes, can do that. Remember to add a comment to say why it is done that way.

**Comment by wkurniawan07** [comment]
I was just about to comment, the PR appears already...
I'd simply do `Config.getAppUrl(...).with*(..., ...)` to resolve this. Won't it work?

**Comment by thyageshm** [comment]
Could you explain a little further? like where to use it...

**Comment by wkurniawan07** [comment]
Get rid of the entire `photoUrl` template (the one with `%s` and stuff) and use:
```java
String studentPhotoUrl = Config.getAppUrl(Const.ActionURIs.STUDENT_PROFILE_PICTURE)
                             .withStudentEmail(...)
                             .withCourseId(...)
                             .withUserId(...)
                             .toString();
```
